#Demo : Array and Matrix Operations

- <h3>Import necessary library

In [1]:
import numpy as np

##Creating Arrays

###Creating a non-dimensional array

In [2]:
non_dim_array = np.array(5)
print("Non-dimensional Array:", non_dim_array)

Non-dimensional Array: 5


###Creating single-dimensional and multi-dimensional arrays

In [3]:
single_dim_array = np.array([1, 2, 3, 4, 5])
multi_dim_array = np.array([[1, 2, 3], [4, 5, 6]])
print("\nSingle Dimensional Array:", single_dim_array)
print("\nMulti Dimensional Array:")
print(multi_dim_array)


Single Dimensional Array: [1 2 3 4 5]

Multi Dimensional Array:
[[1 2 3]
 [4 5 6]]


###Creating arrays of ones and zeros

In [4]:
ones_array = np.ones((3, 3))
zeros_array = np.zeros((3, 3))
print("\nArray of ones:")
print(ones_array)
print("\nArray of zeros:")
print(zeros_array)


Array of ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


###Using arange and linspace

In [5]:
arange_array = np.arange(10)
linspace_array = np.linspace(0, 1, 5)
print("\nArange Array:", arange_array)
print("\nLinspace Array:", linspace_array)


Arange Array: [0 1 2 3 4 5 6 7 8 9]

Linspace Array: [0.   0.25 0.5  0.75 1.  ]


###Copying an array

In [6]:
copied_array = np.copy(single_dim_array)
print("\nCopied Array:", copied_array)


Copied Array: [1 2 3 4 5]


#Arithmetic Operations

In [2]:
a = np.array([10, 20, 30])
b = np.array([5, 10, 15])
print("\nAddition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)


Addition: [15 30 45]
Subtraction: [ 5 10 15]
Multiplication: [ 50 200 450]
Division: [2. 2. 2.]


##Matrix Operations

In [8]:
a = np.arange(0, 9).reshape(3, 3)
b = np.ones((3, 3))
print("\nMatrix A:")
print(a)
print("\nMatrix B:")
print(b)
print("\nMatrix Product:")
print(np.dot(a, b))


Matrix A:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Matrix B:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Matrix Product:
[[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]


## Universal Functions

###Trigonometric functions

In [9]:
angles = np.array([0, np.pi/2, np.pi])
print("\nSine values:", np.sin(angles))
print("Cosine values:", np.cos(angles))


Sine values: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine values: [ 1.000000e+00  6.123234e-17 -1.000000e+00]


###Comparison Functions

In [10]:
comp_array = np.array([1, 2, 3, 4])
print("\nComparison Greater than 2:", np.greater(comp_array, 2))


Comparison Greater than 2: [False False  True  True]


###Math Operations

In [11]:
print("\nSquare Root:", np.sqrt(a))
print("Exponential:", np.exp(a))


Square Root: [[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]]
Exponential: [[1.00000000e+00 2.71828183e+00 7.38905610e+00]
 [2.00855369e+01 5.45981500e+01 1.48413159e+02]
 [4.03428793e+02 1.09663316e+03 2.98095799e+03]]


###Bitwise Operations

In [12]:
bitwise_a = np.array([0, 1, 2, 3])
bitwise_b = np.array([4, 5, 6, 7])
print("\nBitwise AND:", np.bitwise_and(bitwise_a, bitwise_b))
print("Bitwise OR:", np.bitwise_or(bitwise_a, bitwise_b))


Bitwise AND: [0 1 2 3]
Bitwise OR: [4 5 6 7]


###Floating Functions

In [13]:
float_array = np.array([1.1, 2.5, 3.8])
print("\nFloor:", np.floor(float_array))
print("Ceil:", np.ceil(float_array))


Floor: [1. 2. 3.]
Ceil: [2. 3. 4.]


##Aggregate Functions

In [14]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nMatrix:")
print(matrix)
print("\nSum:", np.sum(matrix))
print("Mean:", np.mean(matrix))
print("Standard Deviation:", np.std(matrix))
print("Minimum:", np.min(matrix))
print("Maximum:", np.max(matrix))


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum: 45
Mean: 5.0
Standard Deviation: 2.581988897471611
Minimum: 1
Maximum: 9
