In [7]:
import pandas as pd
import numpy as np
n_dist = np.random.normal(loc=[0.5,1.,10], scale=[3.,3.5,4], size=(10,3))

In [8]:
n_dist

array([[-1.38583932,  7.41075557, 10.93612433],
       [-1.68789516,  5.10440875, 11.9204425 ],
       [-0.9292165 ,  2.42159533,  7.23210206],
       [-0.69846849, -2.38905941, 12.92837758],
       [-2.5111242 , -3.9911911 , 12.56557225],
       [ 0.56833536,  0.2842568 ,  6.48778969],
       [ 2.19096551,  2.11465755,  9.95323286],
       [-3.81007591, -0.60829278, 13.91401191],
       [-1.44932149,  4.53859401,  1.80721642],
       [ 1.98351464,  5.37308419,  8.91207288]])

In [13]:
np.random.randint(0,10, size=(10,3))

array([[5, 6, 9],
       [6, 1, 4],
       [9, 8, 7],
       [1, 6, 0],
       [6, 7, 4],
       [9, 7, 3],
       [5, 0, 0],
       [9, 2, 2],
       [6, 7, 5],
       [5, 7, 1]], dtype=int32)

In [20]:
## values from 0 to 1 of the given shape
np.random.rand(10,3)

array([[[0.05397977, 0.13083573, 0.8512595 ],
        [0.45532843, 0.10374117, 0.21857589],
        [0.71276523, 0.88876185, 0.16012599],
        [0.77256428, 0.75746301, 0.35057613],
        [0.3671264 , 0.2825768 , 0.51265628],
        [0.94201325, 0.09769612, 0.48788127],
        [0.19638608, 0.5961133 , 0.06456439],
        [0.11185286, 0.60455374, 0.48376692],
        [0.87001021, 0.94843859, 0.61076401],
        [0.53164471, 0.63655459, 0.12722711]]])

In [15]:
## std normal distributions values of given shape
np.random.randn(10,3)

array([[-1.31433169,  0.19056129,  0.71370556],
       [-1.04644322, -0.14531192, -1.50071826],
       [ 0.05710498,  0.44096675, -1.36944779],
       [ 0.48724632,  0.95066563, -1.15257806],
       [ 0.44050031,  0.70215624,  1.45342574],
       [-0.56334324, -0.23877053, -2.13863609],
       [-0.59687506,  0.90250831, -1.15212873],
       [ 0.07882428,  0.89360188, -0.40389476],
       [ 0.06109628,  0.05358905, -0.36685935],
       [-0.41988889, -0.40311215, -0.01675879]])

In [22]:
np.random.random(size=(2,3))

array([[0.45731592, 0.07515232, 0.59366864],
       [0.81314887, 0.04389127, 0.9325627 ]])

In [25]:
## seed given the same random values all the time
np.random.seed(101)
np.random.rand(2,3)

array([[0.51639863, 0.57066759, 0.02847423],
       [0.17152166, 0.68527698, 0.83389686]])

In [29]:
np.random.random_sample(5)

array([0.72899276, 0.27623883, 0.68530633, 0.51786747, 0.04848454])

In [34]:
np.random.randint(0,5, size=(2,3))

array([[0, 1, 4],
       [2, 4, 0]], dtype=int32)

In [35]:
np.random.binomial(1,0.5, size=(2,3))

array([[1, 1, 1],
       [1, 0, 0]], dtype=int32)

In [43]:
x= np.linspace(0,10,10)
y = np.sin(x)

x

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [44]:
y

array([ 0.        ,  0.8961922 ,  0.79522006, -0.19056796, -0.96431712,
       -0.66510151,  0.37415123,  0.99709789,  0.51060568, -0.54402111])

In [45]:
np.polyfit(x, y, deg=1)

array([-0.02505018,  0.24617684])

In [51]:
list1 = np.arange(10)
np.random.shuffle(list1)

In [52]:
list1

array([0, 7, 3, 4, 2, 8, 1, 9, 5, 6])

In [53]:
np.argmax(list1)

np.int64(7)

In [54]:
np.argmin(list1)

np.int64(0)

In [57]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
np.round(np.asmatrix(np.random.rand(2,3)).tolist(),2)

array([[0.64, 0.81, 0.67],
       [0.65, 0.42, 0.66]])