In [1]:
import numpy as np

In [2]:
# create boolean array of 3,3
arr = np.full(shape=(3,3),fill_value=True)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [3]:
### empty arr
empty_obj_arr = np.empty(shape=(3,3), dtype=object)
empty_obj_arr

array([[None, None, None],
       [None, None, None],
       [None, None, None]], dtype=object)

In [5]:
empty_int_arr = np.empty(shape=(3,3), dtype=int)
empty_int_arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
empty_str_arr = np.empty(shape=(3,3), dtype=np.str_)
empty_str_arr

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [8]:
iden_arr = np.identity(n=5)

In [9]:
iden_arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
eye_arr =np.eye(5)
eye_arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
b = [1,2,3,4,5,6,1,2,3,4,5]
a = [1,2,3,7,6,5]

arr_ = np.unique_counts(b)
arr_

UniqueCountsResult(values=array([1, 2, 3, 4, 5, 6]), counts=array([2, 2, 2, 2, 2, 1]))

In [58]:
list1 = [(1,2),(3,4),(5,6),(7,8),(9,10)]
np.asarray(list1).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [59]:
t1= ((1,2),(3,4),(5,6),(9,10))
arr_ = np.asarray(t1).reshape(2,4)
arr_


array([[ 1,  2,  3,  4],
       [ 5,  6,  9, 10]])

In [72]:
s1= ((1,2),(3,4),(5,6))
arr_ = np.asarray(s1)
arr_

array([[1, 2],
       [3, 4],
       [5, 6]])