In [1]:
import numpy as np

In [10]:
arr = np.arange(9).reshape(3, 3)

In [11]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
## row no 1 all columns
## [row, col]
arr[1, :]

array([3, 4, 5])

In [18]:
## row no 1 all columns
arr[1]

array([3, 4, 5])

In [22]:
## column 1 values for all rows
arr[:, 1]

array([1, 4, 7])

In [23]:
## specific row and col value
arr[1:2]

array([[3, 4, 5]])

In [25]:
## last row
arr[-1, :]

array([6, 7, 8])

In [69]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [75]:
arr_rev = np.flip(arr)
arr_rev

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [73]:
arr_rev_lr = np.fliplr(arr)

In [74]:
arr_rev_lr

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [77]:
arr_rev_ud = np.flipud(arr)

In [79]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [80]:
arr_rev_ud

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [82]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
arr[1].sum()

np.int64(12)

In [92]:
arr[0:2].sum()

np.int64(15)

In [93]:
arr[:].sum()

np.int64(36)

In [94]:
arr[:].mean()

np.float64(4.0)

In [95]:
np.median(arr)

np.float64(4.0)

In [96]:
np.mean(arr)

np.float64(4.0)

In [97]:
np.std(arr)

np.float64(2.581988897471611)

In [98]:
np.var(arr)

np.float64(6.666666666666667)

In [99]:
np.sort(arr)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [105]:
num_arr = [10, -1, 23, 100, 21, -2, -9, 4]

In [108]:
num_arr.sort(reverse=False)

In [109]:
num_arr

[-9, -2, -1, 4, 10, 21, 23, 100]

In [110]:
num_arr = np.arange(0, 10)

In [116]:
## odd
num_arr[1::2]

array([1, 3, 5, 7, 9])

In [117]:
## even
num_arr[0::2]

array([0, 2, 4, 6, 8])

In [123]:
## provide arrays as tuple or list to make it horizontal
a = [1, 2, 3]
b = [4, 5, 6]

h_arr = np.hstack((a, b))

In [124]:
h_arr

array([1, 2, 3, 4, 5, 6])

In [125]:
h_arr = np.hstack([a, b])

In [130]:
v_arr = np.vstack([b, a])

In [131]:
v_arr

array([[4, 5, 6],
       [1, 2, 3]])

In [132]:
np.hstack(v_arr)

array([4, 5, 6, 1, 2, 3])

In [136]:
my_arr = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]

In [165]:
my_matrix = np.array(my_arr)

In [166]:
my_matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [167]:
### get first 2 rows and first 2 columns
new_mat = my_matrix[0:2, 0:2]

In [168]:
new_mat.shape

(2, 2)

In [176]:
my_matrix

array([[ 0,  2,  0,  4],
       [ 0,  6,  0,  8],
       [ 0, 10,  0, 12],
       [ 0, 14,  0, 16]])

In [177]:
my_matrix = np.array(my_arr)

In [179]:
my_matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [193]:
bol_arr = np.arange(1,17).reshape(4,4)

In [194]:
bol_arr[bol_arr % 2 ==0] = 0

In [195]:
bol_arr

array([[ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0]])

In [196]:
bol_arr[bol_arr % 2 ==1] = 1

In [198]:
bool_arr = np.array(bol_arr, dtype=bool)

In [199]:
bool_arr

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [201]:
my_matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [206]:
my_matrix[bool_arr].reshape(4,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])