In [61]:
import numpy as np

In [62]:
arr = [1, 2, 3]
type(arr)

list

In [63]:
np.array(arr)

array([1, 2, 3])

In [64]:
# gives ndarray type when created using numpy
type(np.array(arr))

numpy.ndarray

In [65]:
# numpy array ... no of ways to create it apart from above
range_arr = np.arange(10, 0, -1)

In [66]:
range_arr

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [67]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
np.ones((1, 2))

array([[1., 1.]])

In [70]:
np.ones([1, 2])

array([[1., 1.]])

In [71]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [72]:
arr = np.arange(1, 6)

In [73]:
arr + arr

array([ 2,  4,  6,  8, 10])

In [74]:
arr - arr

array([0, 0, 0, 0, 0])

In [75]:
arr * arr

array([ 1,  4,  9, 16, 25])

In [76]:
arr / arr

array([1., 1., 1., 1., 1.])

In [77]:
np.exp2(arr)

array([ 2.,  4.,  8., 16., 32.])

In [78]:
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [79]:
arr = np.ones((3, 3), dtype=bool)

In [80]:
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [81]:
arr = np.zeros((3, 3), dtype=bool)

In [82]:
arr

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [83]:
np.linspace(0,50,11)

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [84]:
np.linspace(0,70,11)

array([ 0.,  7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

In [85]:
arr = np.arange(16)

In [86]:
np.random.shuffle(arr)
arr.reshape(4,4)

array([[ 1, 13,  8,  5],
       [ 4, 14,  0,  7],
       [ 3,  6,  2, 12],
       [11,  9, 15, 10]])

In [87]:
arr1 = np.arange(0,4)
arr2 = np.arange(4,8)
arr3 = np.arange(8,12)
arr4 = np.arange(12,16)

arr= np.array([arr1, arr2, arr3, arr4])

In [88]:
arr.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [89]:
arr[0]

array([0, 1, 2, 3])

In [90]:
arr[:,-1]

array([ 3,  7, 11, 15])

In [91]:
arr[:, :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [92]:
arr[:, -2].reshape(4,1)

array([[ 2],
       [ 6],
       [10],
       [14]])

In [93]:
dia_arr = np.arange(9).reshape(3,3)

In [94]:
dia_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [95]:
np.diag(dia_arr,k=1)

array([1, 5])

In [96]:
np.diag(dia_arr,k=0)

array([0, 4, 8])